# Generated by Django 4.1.2 on 2022-10-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinkled', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gps',
            name='long',
            field=models.FloatField(default=0.0),
        ),
    ]
