# Generated by Django 4.1.2 on 2022-10-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinkled', '0002_gps_lat_gps_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gps',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
